# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_galleryimage_image_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved')],
                default='approved',
                max_length=20,
            ),
        ),
    ]
