# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customerreview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('tag', models.CharField(default='Customer AI', max_length=80)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('metric_one_value', models.CharField(blank=True, max_length=40)),
                ('metric_one_label', models.CharField(blank=True, max_length=120)),
                ('metric_two_value', models.CharField(blank=True, max_length=40)),
                ('metric_two_label', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
    ]
